name: MCPrefixAchievement
version: '1.1.0'
main: com.github.silvertreekr.mcprefixachievement.MCPrefixAchievement
api-version: '1.21'
authors: [ SilverTreeKR ]
dependencies:
  server:
    CustomItems:
      load: BEFORE
      required: true
      join-classpath: true